spring:
  application:
    name: Music API
  datasource:
    url: jdbc:h2:mem:music
    username: music
    password: music
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console